import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-300`}
      >
        <nav className="flex  w-full justify-center bg-black text-white gap-2">
          <Link className="hover:bg-white hover:text-black my-2 px-4 py-1" href="/">Home</Link>
          <Link className="hover:bg-white hover:text-black my-2 px-4 py-1" href="/aboutus">About</Link>
          <Link className="hover:bg-white hover:text-black my-2 px-4 py-1" href="/products">Products</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
